// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czslqvdhugudzvximddj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6c2xxdmRodWd1ZHp2eGltZGRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NzYyMTAsImV4cCI6MjA2NDI1MjIxMH0.6JfDj6Yh2D-wVmqPqBWSWwjdzpiFjYHy5kdr2xQo3U8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);